### ISSUE TITLE
Implement the DRY method

### ISSUE THREAD

**Issue by mmsesay** [chuanqizhu0820/To-Do-List#9]
Good job @chuanqizhu0820, the team is really glad for your progress and have to make few suggestions:

- We are suggesting you create a method that can handle the saving of items to the local storage. The following code is seeing repeated in the task.js file: 
  - https://github.com/chuanqizhu0820/To-Do-List/blob/ad0be5218f9fd80c4c7ac9af87ca3d5342b98d8b/src/tasks.js#L16-L17
  - https://github.com/chuanqizhu0820/To-Do-List/blob/ad0be5218f9fd80c4c7ac9af87ca3d5342b98d8b/src/tasks.js#L27-L28
  - https://github.com/chuanqizhu0820/To-Do-List/blob/ad0be5218f9fd80c4c7ac9af87ca3d5342b98d8b/src/tasks.js#L71-L72
  - https://github.com/chuanqizhu0820/To-Do-List/blob/ad0be5218f9fd80c4c7ac9af87ca3d5342b98d8b/src/tasks.js#L88-L89

**Comment by chuanqizhu0820** [comment]
thank you, @mmsesay. your suggestion is very helpful.

**Comment by mmsesay** [comment]
The pleasure is all mine @chuanqizhu0820
